### ISSUE TITLE
[CJB Cheats Menu] add support for custom skills

### ISSUE THREAD

**Issue by Traktori7** [CJBok/SDV-Mods#111]
Add entries to the skill tab to support custom skills and their professions. Examples of new skills:
https://www.nexusmods.com/stardewvalley/mods/522
https://www.nexusmods.com/stardewvalley/mods/521
https://www.nexusmods.com/stardewvalley/mods/2007

**Comment by Pathoschild** [comment]
Thanks for the suggestion! Unfortunately there's no easy way to detect custom skills due to the way they work, so I don't currently have any plans to implement it. A pull request is welcome if someone finds a clean way to do it, but I'll close this in the meantime since GitHub issues are only used for planned development.

**Comment by Traktori7** [comment]
I understand. Then what do you think of implementing an API through which mods could register their skills with the cheat menu? Mods could provide a list of professions and define an event handler that listens to changes in the settings regarding them. Although it would require custom skills to comply with the api, it'd atleast provide an easy way to reset them.

Do you see any problems with this kind of approach?
